language: c
git:
  depth: false
script: 
  - make 
  - ctest -VV
jobs:
  include:
      - name: "gcc release static no py module"
        compiler:
          - gcc
        before_script:
          # create a build folder for the out-of-source build
          - mkdir build
          # switch to build directory
          - cd build
          # run cmake; here we assume that the project's
          # top-level CMakeLists.txt is located at '..'
          - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DBUILD_PYTHON_VNR_MODULE=OFF .. 
      - name: "clang release static no py module"
        compiler:
          - clang
        before_install:
          # Just for clang
          - export LD_LIBRARY_PATH=/usr/local/clang/lib:$LD_LIBRARY_PATH
        before_script:
          # create a build folder for the out-of-source build
          - mkdir build
          # switch to build directory
          - cd build
          # run cmake; here we assume that the project's
          # top-level CMakeLists.txt is located at '..'
          - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DBUILD_PYTHON_VNR_MODULE=OFF .. 
      - name: "gcc release dynamic no py module"
        compiler:
          - gcc
        before_script:
          # create a build folder for the out-of-source build
          - mkdir build
          # switch to build directory
          - cd build
          # run cmake; here we assume that the project's
          # top-level CMakeLists.txt is located at '..'
          - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_PYTHON_VNR_MODULE=OFF .. 
      - name: "clang release dynamic no py module"
        compiler:
          - clang
        before_install:
          # Just for clang
          - export LD_LIBRARY_PATH=/usr/local/clang/lib:$LD_LIBRARY_PATH
        before_script:
          # create a build folder for the out-of-source build
          - mkdir build
          # switch to build directory
          - cd build
          # run cmake; here we assume that the project's
          # top-level CMakeLists.txt is located at '..'
          - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_PYTHON_VNR_MODULE=OFF .. 
      - name: "gcc release static with py module"
        compiler:
          - gcc
        before_install:
          # Just for python module build
          - sudo apt-get install -y swig3.0
          - sudo pip install --upgrade pip
          - sudo pip install numpy
        before_script:
          # create a build folder for the out-of-source build
          - mkdir build
          # switch to build directory
          - cd build
          # run cmake; here we assume that the project's
          # top-level CMakeLists.txt is located at '..'
          - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DBUILD_PYTHON_VNR_MODULE=ON .. 